### ISSUE TITLE
Web sockets returning 400

### ISSUE THREAD

**Issue by eah13** [mtgred/netrunner#128]
I can create but not connect to a game and found these errors in the console

![screenshot 2015-02-25 at 8 24 03 pm](https://cloud.githubusercontent.com/assets/1702745/6386372/53744c8a-bd2c-11e4-8adc-c7fdfb00ded4.png)

Chrome Version 40.0.2214.114 (64-bit)

**Comment by mtgred** [comment]
Thanks for reporting the issue. There were some server problems last week. Everything should be ok now.

**Comment by eah13** [comment]
This happens regardless of server status- I think it's related to Automattic/socket.io#1942

**Comment by tylercb** [comment]
Had the same issue, my app is behind nginx. Making these changes to removed the error.

location / {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

This is originally from https://chrislea.com/2013/02/23/proxying-websockets-with-nginx/

**Comment by mtgred** [comment]
The issue came from Cloudflare. It should be fixed now.

**Comment by mtgred** [comment]
The problem has been finally fixed. The problem came from a combination of configuration issues in NginX and Cloudflare.

Jinteki.net now operates with websockets instead of the long polling fallback.

**Comment by eah13** [comment]
:beers: No more console error!  Site seemed much faster and more stable on a quick game just now.

**Comment by f0rmat1k** [comment]
still get this error (heroku + cloudflare)

**Comment by SNAPPRO** [comment]
still gets this error , node application hosted on openshift  (for real time chat and notifications) and other stuff in PHP
