### ISSUE TITLE
Feedback on Deck Stats and Gameplay Stats in General

### ISSUE THREAD

**Issue by rnw** [mtgred/netrunner#2838]
Hi everyone,

Firstly, amazing work on Jinteki.net. My biggest appreciation comes from how accessible Jinteki.net has made the game to my humble meta, for whom getting together to shuffle physical cards isn’t always practical. Cheers!

Yesterday I saw Jinteki.net now features Deck Stats and was initially really excited. (In the two-week period leading up to my Regionals, I played 197 games on Jinteki.net, spreadsheeted each deck’s performance using my own metrics, then subsequently abandoned the results and decided on Desperado Smoke the night before.)

As I thought about this new feature more, I a) had some reservations about the impact it may have over time, and b) returned to some thinking I was doing earlier in the year as to how you might be able to use gameplay stats on Jinteki.net as a way of addressing some of the pains the community expresses and some of the challenges new players face when learning the game.

What follows is an analysis of sorts. Obviously, you can take it or leave it in whatever way you choose. My thinking is in large part informed by spending the last several years managing UX/UI teams, designing and releasing new features and sometimes having them fail, conducting focus groups and workshops to understand how users really used what we made, and sometimes getting yelled at by executives. I know you folks all work for free on this, so just consider it feedback for your own discussion if you feel like it. If there's anything you feel warrants more discussion or if you think I can be helpful in some way just ping me @harbord on Slack.

# About “Play Goals”

Jinteki.net obviously supports a multitude of player personas with a multitude of play goals ("What do I want out of this?"), from single-core beginners to Twitch-streamed tourneys featuring the best players in the world. At the single-core end of the spectrum, the play goals are quite clear (“Learn the game, have fun while doing so”) and at the highest-tier end of the spectrum, the player goals are also quite clear (“Compete at the highest level, have fun while doing so”). In the centre, however, we appear to have a majority of player goals which are more mutable (“Play to win… on Mondays, play to prepare for IRL tournament, play to relax. Homebrew or jank. Full card pool or limited card pool. Draft or 1.1.1.1 or Cache Refresh.”). (As a side note, there are also two other personas to consider, and they are broadcaster/content creator and viewer/spectator, but less on those for now.) 

Crucially, most players will inhabit three or four of these states over time, or move back and forth along the spectrum based on other factors. Using this concept helps add more nuance to the distinction between “Competitive Player” and “Casual Player,” instead treating all users as players who may sometimes share one or another goal.

# Lobby Politics

Along those lines, it has been sometimes noted the bipartisan “Casual” vs “Competitive” lobby structure of Jinteki.net can be problematic. We only have to look at the number of active games in each lobby to confirm that something is probably not working. Separating the lobbies was initially a very good move, but over time it may have become confusing and has certainly resulted in some players having less fun rather than more. A few examples of things I've seen or heard:

- “You’re playing [card or ID]?… Shouldn’t you be in Competitive?”
- “Oh my god you won’t believe how salty my opponent was earlier when I [did normal Netrunner].”
- “I didn’t say you could take that back.”
- xBladeKiller719x has disconnected…
- “I’m testing for a tournament. The randomness of the Casual lobby isn’t helping my decks, but I never get a game in Competitive.”

My primary concern regarding implementation of gameplay stats—if they're done in the same way for every type of game and every type of player—is that it could lead to a state where those with the play goal of improving and defending their gameplay stats will do so at the detriment of the diverse play goals of the Casual lobby, where statistically most games are played. Defending your win rate is natural and normal—I do it, when I’m in that kind of mood—but it’s problematic without giving users any tools to identify those who share that goal (or perhaps to avoid those who don’t).

My secondary concern here is that the feature simply appeared, apparently without discussion among the community or an attempt to get a picture of how the feature would be received. It would be a great idea to broadly consult the community when changes like these are planned. In practical terms, it could help the Jinteki.net dev team preemptively handle edge cases or write test cases. In fluffier terms, demonstrating in some way that different play goals were considered in changes/new features to the platform would help reinforce that Netrunner is a diverse and friendly community.

# Rewarding Different Play Goals By Using Gameplay Stats Differently

it’s impossible to legislate whether a card, an ID, a deck, or an entire playstyle are “casual” or “competitive” in game that has a large card pool and extremely variable power levels. Similarly, it’s also very difficult to legislate for player skill. 

However, one of the great things about this recent decision to implement gameplay stats in some capacity is that they could be used to reward different play goals... differently... by recording and displaying gameplay stats or not depending on the game type (which I guess we can treat as the “lobby.”). The end result might be a "healthier" online metagame. I sat down and thought about how this might break down:

1. Casual Game. (_“No statistics will be displayed or shared related to players, decks, or the outcome of this game. The Jinteki.net dev team may analyze anonymized, aggregated stats to help support and develop the platform.”_)
2. Competitive Game. (_“Both players agree that their win rate and Deck Stats may go up or down by participating in this game.”_) Presumably this is more rewarding if there are metrics other than simply Deck Stats at stake...

There are also third and fourth types of game of I considered, but they’re less fleshed out and I can’t decide if they should be “modal” or not. For example, can one player be testing for a tournament at the same time that they consider the game to be casual or competitive for the purposes of gameplay stats on Jinteki.net? Hard to say without more analysis.)

3. Testing/Tournament Prep Game. (_“Your deck’s stats are adjusted as a result of this game, but the result of the game does not count for competitive win rates.” Or, “Players select Casual or Competitive, but either player may silently flag that they are testing, which alters how Deck Stats are displayed.”_)
4. Streamed Game. (_“The games stats are still recorded normally depending on the game type, but they’re not displayed in order to allow you—as an example—to not alert your audience to the fact that the deck you’re playing is one you’re considering for an upcoming tournament or one that you have been sucking at.”_)

# Benefits of Rewarding Play Goals

So you say, "What's the point, if people aren't using the Competitive lobby, or sometimes feel their opponent _should_ be using it, how could implementing more nuanced stats help?" Well there are benefits for everyone:

- Incentivizes the natural competitiveness of players who wish to play competitively by offering them the ability to test their skills against others who currently share that goal (“This one counts, bring your best deck”.) and rewarding them with stats.
- Deemphasizes the sensitive distinction between “Competitive Player” and “Casual Player,” instead treating all users as players who may sometimes share some kind of play goal and letting them know how they'll be rewarded for pursuing either goal.
- Discourages day-to-day smurfing by allowing all players the ability to test a goofy Professor deck in casual games without harming their win rate as a player or test a new card without harming their favourite deck’s win rate. (Obviously smurfing for tournament prep is always a thing, I sure as hell do it.)
- Discourages sharking (maybe that’s too strong a word). As an example, if I choose to play a Casual Game with my evil Austerity CI deck, I won't get any reward out of it in terms of stats. Players who are just learning, prefer not to play tier 1 decks, or don’t really care about the outcome of the game can therefore be more confident that their opponent shares the same goal by knowing that their opponent has less to gain by winning.
- Makes spectating games more exciting if you know each player might have something on the line.
- Provides a more accurate picture of the competitive meta for testing purposes.

And of course…

- Facilitates further enhancements to displayable gameplay metrics without jeopardizing a space where just-for-fun play is always possible and encouraged. Some examples:
-- Some degree of matchmaking via visibility into a potential opponent’s displayable stats
-- Leaderboards (I think a lot of people would love this, but it would have to be handled carefully.)
-- “Sets” (groups of games considered together for the purposes of gameplay stats, which may correspond to a tourney among friends, a test cycle, an online league or anything else).

**Comment by danhut** [comment]
@rnw Thanks for the feedback.  I implemented this set of functions and share some of the same concerns.  I will argue that everything on JNET just "appears" and if something is a problem the team will get rid of it too.  In fact the functionality has been requested for a long time.

What I just implemented was the option for a player to opt-out of both deck and game-wise win/loss stats.  Please take a look here:
https://github.com/mtgred/netrunner/pull/2831

I have some future ideas - but think allowing a user to opt-out is the least work code-wise and takes care of most concerns.

Here is how it will work once this goes live - assuming MTGRED accepts the change into the code base.

**Game Stats**
- For everyone we will track games started and games completed
- My goal here is to avoid people dropping out of games without completing them
- Right now a user can also reset their stats at any time - again as I am not trying to alienate people
- A users completion rate is exposed into the game lobby  - noting if they have less than 10 games total we show nothing
- We *could* block users from clearing their completion rate but not looking to upset anyway here.  Possibly we could abstract the raw % into something look "Good","Bad"
- Users can opt-in or opt-out of tracking their overall win/lose rate.  If they opt out nothing is shown or sent to the back-end

**Deck Stats**
- Now able to be disabled completed
- If you disable nothing is shown OR logged to the backend at all
- User can reset stats at any time

I had some future enhancements in mind already - just takes time and I'd rather get feedback like yours rather than not launch the features
- Ability to have stats in Casual vs. Competitive lounge
- Abstraction of game completion rate to "Good" "Awesome" "Bad"
- More smarts in "Incomplete" counter such that if your opponent drops first, you don't get "blamed". Though I think abusive droppers will have the worst stats here and my aim is defaintely to irradicate this behaviour.
- Find out how to push stats via AJAX rather than need user to do a "refresh" for a few cases

I think the other tweaks you suggest are good - and something to be considered if we were trying to create a league table - certainly I am not right now though someone in the team might want to.

Personally I do not want to expose stats for every deck into a single GUI across players - nor analyse exact win rates per deck/card vs other factions.

Thoughts?

**Comment by danhut** [comment]
BTW for the Casual vs. Competitive lounge not working - could be good feedback - just not something I was trying to address through Stats.  I do see your point - I don't have a better idea though.

**Comment by danhut** [comment]
I have implemented these 3 features now.  In my view this is a pretty solid system - once live the only thing I want to add is to stop people clearing their incomplete games so we know who abusers are.  

- Ability to have stats in Casual vs. Competitive lounge
- More smarts in "Incomplete" counter such that if your opponent drops first, you don't get "blamed". This also interworks with the awesome new rejoin function
- Stat updates are pushed when a game is completed

**Comment by rnw** [comment]
Hi Dan,

I think a Rejoin feature is an amazing idea and the community would love it! Regarding stats, though, it does seem there's an emphasis on recording statistics for completed/vs non-completed games in these updates. What's the rationale behind implementing it this way? I would say the underlying issue for game non-completion is a) the unclear distinction between "casual" and "competitive" and/or b) the lack of matchmaking around player goals (basically the substance of my original post). Incentivizing game completion without understanding why games aren't completed might a) artificially keep users in games they'd rather not play, which may ultimately result in b) fewer active users over time since "I can't drop a game against Industrial Genomics without being 'blamed,' when ideally I would like to have more agency into how to avoid players and matchups that do not suit me." Further, how can Jinteki.net know the conditions under which the game was abandoned? Almost all of my abandoned games are between friends during a testing effort (we may quickly begin and abandon 5 or 10 games to test a deck's speed, for example).

I guess the underlying intention of my original post was to show that changes like these are not trivial. If it can have an impact on how fun or rewarding the experience of online Netrunner is for any number of users, it would be a good idea to collect community feedback from the outset and be prepared to demonstrate how that was considered in order to show that the changes are accountable to the community. Just something I learned by getting yelled at as Product Manager if we released a feature users didn't like or didn't understand...

**Comment by JoelCFC25** [comment]
> What's the rationale behind implementing it this way?

A longstanding problem with a class of user that jumps out of a game the instant they see a particular card they deem "unfair" or NPE or whatever term you like. Players who are on the site in an earnest effort to just play games get understandably aggravated that their time has been wasted. 

> "I can't drop a game against Industrial Genomics without being 'blamed,' when ideally I would like to have more agency into how to avoid players and matchups that do not suit me."

I still don't understand what is insufficient about the idea that players should attempt to hash out with a potential opponent prior to hitting "Start Game" if it is really _that_ important to them. The ability to communicate via chat seems like plenty of agency. 

The early reaction to the idea of an abstracted gauge of a user's propensity to see a game through has been quite positive as far as I've seen.

**Comment by danhut** [comment]
I would ask for some concrete bullet points on what you think could be done.  Maybe it is as simple as adding a testing room where nothing is logged at all?

**Comment by HongkongKoma** [comment]
No doubt, I really like the new feature. But since it is implemented, I have gotten the impression that a lot more of my opponents try to manipulate their/my stats by leaving the game before it technically ends, e.g. when I'm at 6 points and about to access the winning agenda, they type "gg" and leave me alone with the game with no possible option end it in a correct manner.
 
So it would be better I guess that a game is considered a loss in his stats for the player who (rage)quits before it's technically over (by points, decked or flatlined).

**Comment by x3N1GM4x** [comment]
I think that's the purpose the the game completion stat @HongkongKoma - so if someone leaves a game before it's over, it is recorded as an incomplete game for them. People can then use the game completion % for potential opponents to decide if they want to play that person. So someone who quits like this all the time should end up with a low game completion % and therefore find it harder to get games.

Perhaps when an opponent leaves the game without conceding, this should be counted as a game win for the player who did not leave (if it's not already @danhut?).

**Comment by Saintis** [comment]
My concern is (and this might be the case here) that people can just "ghost" the game and refuse to leave or concede, staying in the game until you are force to hit concede to play another game.

Implementing a time-out timer for people who just "ghost" the game might be a solution.

**Comment by HongkongKoma** [comment]
@x3N1GM4x I confess I do not fully understand the completion % - I thought that a player who is left back also is affected? If not, that's good. You second paragraph is what I also think is a good idea. 
Let's think about that in a real life match: You play a game and your opponent, seeing he's gonna lose,  suddenly takes his cards and leaves the table. What would a judge do? Game loss for the quitter (or game win for the guy left behind, still scratching his head), I think.

@Saintis I never saw this, but it's possible of course. But the person who "ghosts" can also not play a next game. In the netrunner floor rules, stalling a game is penalized with a game loss.

**Comment by danhut** [comment]
I am not keen to credit a win to someone if the opponent leaves.  Open to other forms of abuse... I hoped the games incomplete counter would be enough to to put people off.  

Here is the entire logic right now for both user and deck stats:

- On game start we increment games-commenced counter +1
- On game being won we add data to game state to indicate who and which deck won
- If a 1st player drops from the game, we update state to flag the remaining player
- If the 1st player rejoins, we clear that flag
- On final person leaving the game (player or spectator), we update stats again
- If there is a winner, we log a completion and a win to that user/deck
- If there is a loser, we log a completion and a lose to that user/deck
- If no winner, we log a completion to the last player to leave
- The first player to leave gets an incomplete game

I don't know how someone can get a 109%... I have to assume a glitch with logging a game-start into the database.  I cannot reproduce and would need to know how.

**Comment by HongkongKoma** [comment]
Thanks for your clarifications.
